version: '3'

services:
  db: # Use root/example as user/password credentials
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  flaskapp:
    build: ./flaskapp
    volumes:
      - ./flaskapp:/usr/src/app
    depends_on:
      - db
    ports:
      - 5000:80
